# Generated by Django 3.1.6 on 2021-10-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='moblie',
            new_name='mobile',
        ),
    ]
